library(tidyverse)


## @knitr highchart1
library(highcharter)

myData <- read.csv("data/demo.csv")


#colnames(myData)
#  [1] "JURISDICTION_NAME"                   "COUNT_PARTICIPANTS"                  "COUNT_FEMALE"                       
#  [4] "PERCENT_FEMALE"                      "COUNT_MALE"                          "PERCENT_MALE"                       
#  [7] "COUNT_GENDER_UNKNOWN"                "PERCENT_GENDER_UNKNOWN"              "COUNT_GENDER_TOTAL"                 
# [10] "PERCENT_GENDER_TOTAL"                "COUNT_PACIFIC_ISLANDER"              "PERCENT_PACIFIC_ISLANDER"           
# [13] "COUNT_HISPANIC_LATINO"               "PERCENT_HISPANIC_LATINO"             "COUNT_AMERICAN_INDIAN"              
# [16] "PERCENT_AMERICAN_INDIAN"             "COUNT_ASIAN_NON_HISPANIC"            "PERCENT_ASIAN_NON_HISPANIC"         
# [19] "COUNT_WHITE_NON_HISPANIC"            "PERCENT_WHITE_NON_HISPANIC"          "COUNT_BLACK_NON_HISPANIC"           
# [22] "PERCENT_BLACK_NON_HISPANIC"          "COUNT_OTHER_ETHNICITY"               "PERCENT_OTHER_ETHNICITY"            
# [25] "COUNT_ETHNICITY_UNKNOWN"             "PERCENT_ETHNICITY_UNKNOWN"           "COUNT_ETHNICITY_TOTAL"              
# [28] "PERCENT_ETHNICITY_TOTAL"             "COUNT_PERMANENT_RESIDENT_ALIEN"      "PERCENT_PERMANENT_RESIDENT_ALIEN"   
# [31] "COUNT_US_CITIZEN"                    "PERCENT_US_CITIZEN"                  "COUNT_OTHER_CITIZEN_STATUS"         
# [34] "PERCENT_OTHER_CITIZEN_STATUS"        "COUNT_CITIZEN_STATUS_UNKNOWN"        "PERCENT_CITIZEN_STATUS_UNKNOWN"     
# [37] "COUNT_CITIZEN_STATUS_TOTAL"          "PERCENT_CITIZEN_STATUS_TOTAL"        "COUNT_RECEIVES_PUBLIC_ASSISTANCE"   
# [40] "PERCENT_RECEIVES_PUBLIC_ASSISTANCE"  "COUNT_NRECEIVES_PUBLIC_ASSISTANCE"   "PERCENT_NRECEIVES_PUBLIC_ASSISTANCE"
# [43] "COUNT_PUBLIC_ASSISTANCE_UNKNOWN"     "PERCENT_PUBLIC_ASSISTANCE_UNKNOWN"   "COUNT_PUBLIC_ASSISTANCE_TOTAL"      
# [46] "PERCENT_PUBLIC_ASSISTANCE_TOTAL"    

hchart(myData, "scatter", hcaes(x = COUNT_MALE, y = COUNT_FEMALE))
